name: ci

on:
  pull_request:
      branches: [ "*" ]
  push:
      branches: [ master ]
      tags-ignore: [ "*" ]

jobs:
  Lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM@11
      run: npm install npm@11 -g

    - name: Install dependencies
      run: npm i

    - name: Lint JavaScript files using ESLint
      run: npm test
