name: ci

on:
  pull_request:
      branches: [ "*" ]
  push:
      branches: [ master ]
      tags-ignore: [ "*" ]

jobs:
  Lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
    - uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install corepack
      if: (matrix.node-version != '14.x')
      run: npm i -g corepack

    - name: Install Yarn
      run: corepack prepare yarn@stable --activate

    - name: Install dependencies
      run: yarn

    - name: Lint JavaScript files using ESLint
      run: npm test
